service:
  name: aws-lambda-nodejs-graphql

frameworkVersion: ">=1.45.1 <2.0.0"

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    DYNAMO_DB_TABLE: ${self:service.name}-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMO_DB_TABLE}

functions:
  query:
    handler: src/handler.main
    events:
      - http:
          path: query
          method: GET
          cors: true
    package:
      include:
        - src/handler.js
        - src/graphql.js
        - src/dynamodb.js
        - node_modules/uuid/**
        - node_modules/graphql/**
        - node_modules/iterall/**
  
package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - src/**
    - .git/**
    - .serverless/**
    - .idea/**
    - .vs/**
    - node_modules/**
    - babel.config.js
    - yarn.lock
    - package.json
    - README.md
    - LICENSE

resources:
  Resources:
    OrdersDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: ${self:provider.environment.DYNAMO_DB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1